### ISSUE TITLE
Not really an issue, just a feedback on Prestige icons. 

### ISSUE THREAD

**Issue by Posister** [daleao/modular-overhaul#145]
Hello i just edited sprites to make them look more appealing (at least to me). I did not found any way to contact you any other way (may be im blind, sorry for that). Anyway just wanted to ask for a feedback :) thank you!
![professions](https://github.com/daleao/modular-overhaul/assets/139913113/2d75e821-1858-4963-808f-b6bf533bb4c5)

**Comment by daleao** [comment]
Looks pretty good. I think the Spelunker icon looks a little flat by comparison with the others, probably just because of the original isn't great to begin with.
I personally really like the "metallic" look achieved by the contrasting blacks (even though it's just some filters applied over the regular icons). But I can see how others might prefer the cleaner golden look you achieved here.
Would you like me to include your sprites as a config option?

**Comment by Posister** [comment]
Yes, i would love to! :)

**Comment by daleao** [comment]
Added in 4.2.2.
