### ISSUE TITLE
Future Updates for SDV 1.6?

### ISSUE THREAD

**Issue by JustJulzz** [daleao/modular-overhaul#184]
Will this mod be updated for SDV Version 1.6?
If so, when will it be updated?

**Comment by TruePotato12** [comment]
Per the SV Discord 

Since a lot of people have been asking about MARGO update this will be my official announcement about it:

Obviously a lot has changed in 1.6. Not just in terms of base game code changes, but also new content. Both of these things have huge impact to MARGO.

MARGO was originally coded to make surgical changes to the vanilla code (i.e. mostly transpilers) in order to be as lightweight as possible, and that has gloriously backfired since now most of it needs to be rewritten. And there's no way to know in advance what needs to be rewritten, which means effectively I need to redo everything. MARGO is a huge mod with almost 200 of these surgical changes and hundreds of thousands of lines of code. Imagine my enthusiasm to get started.

With the new content changes, several MARGO features are obsolete, yet others will need to be rebalanced. That is to say, it's not just a matter of updating the code, but conceptually the whole mod needs to be revised.

So the TL;DR:
Yes, I do intend to update it.
No, I have not even started.
When I do, it will take time. May not even come out this year.
Whenever the update comes out, it will probably be a very different mod.

I suggest everyone try out Kedi's talent mod when that comes, which will be much sooner than the MARGO update.

Please help to spread the message if you see people asking about MARGO.
