### ISSUE TITLE
Quest Progress lost on update

### ISSUE THREAD

**Issue by canis-lupus03** [daleao/modular-overhaul#28]
Hello, 

when I updated to the newest version today, I lost all progress on the "A Hero's Journey" quest. When I updated to 3.1.2 a few days ago, it reset the Valor component but not the others, but now it's all at zero. 

I updated by overwriting the folder rather than deleting the old one and putting the new one in, if that matters. 

(I hope this is the right place to report this, since the mod isn't on nexus anymore.)

**Comment by daleao** [comment]
Can you share the save folder from before the update?

**Comment by canis-lupus03** [comment]
I've not specifically made a copy of it, and just played one day since updating, but if you tell me where to find that folder and how to share it, I can?

**Comment by daleao** [comment]
Look inside the SaveBackups mod.

**Comment by victrosia** [comment]
The same thing happened to me. I fulfilled the requirements I had missing (aka I had 1/3 honor and 1/3 compassion so I finished the missing 2 requirements) and was hoping I could find the quest ID to complete the quest via commands in SMAPI.

**Comment by daleao** [comment]
There is a mistake in the code for migrating from the legacy data keys to the new ones.
If you have not yet saved your game, or you still have access to the save from before updating, then use [this debug version](https://github.com/daleao/modular-overhaul/releases/download/3.1.3/ModularOverhaul.3.1.3-VirtueDataHotfix.zip) for at least one day. This will correctly migrate your old quest data to the new format.

Otherwise, if you have already saved your game, this version will not work. Use either the Event Repeater mod to replay the heart events which are described [here](https://github.com/daleao/modular-overhaul/tree/main/Modules/Combat#faq). Or alternatively, just use this mod's console commands to skip the quest entirely (`cmbt adv compassion`, `cmbt adv honor`, etc.).
