### ISSUE TITLE
is there a way to re-trigger the blade of ruin quest

### ISSUE THREAD

**Issue by jjssnn93** [daleao/modular-overhaul#36]

**Comment by jjssnn93** [comment]
after i went to the wizard, it triggers a cutscene but i can't find the quest in the quest list. and now the wizard is saying that i ignore his warning.

**Comment by daleao** [comment]
The Wizard will claim that you "ignored his warning" if and only if you saw the cutscene and continued to use the Blade of Ruin to defeat another 50 enemies.

Since you had time to do that then I suppose it's been a while since you saw the cutscene, which means the quest might be lost in your journal. Look for either "The Blade of the Ruined Hero" or "Hero's Journey".

If you really can't find either of those, then you can force the quest using the console command `cmbt adv hero`

**Comment by jjssnn93** [comment]
thankyou so much for the assistance!

**Comment by andip23** [comment]
Follow-up question! I have accidentally killed a lot of enemies with the blade of ruin because of the auto-equipping. Will I still be able to lift the curse, or did I need to rid it of the curse before killing 50 more enemies with the blade?? Also, could you give more specifics on how much of each thing needs to be accomplished to lift the curse? I've been trying really hard and nothing's happening.
