### ISSUE TITLE
Tool Power Select not affecting pickaxe / axe

### ISSUE THREAD

**Issue by JackYevhen** [daleao/modular-overhaul#49]
***Tool Power Select*** is not working with ***MARGO***, so please easier make it so ***Tool Power Select*** works for Pickaxe / Axe, or for example, add a setting with charge delay, or maybe bake fitchure of selecting default power level of tool inside ***MARGO***.

**Comment by daleao** [comment]
I will not add compatibility for Tool Power Select.

However you can already do this (sort of) by changing the radius of the tool at each power level in the tool settings. By default this is set to be progressive (1-2-3-etc..), but you can increase the copper radius to whatever number you want so that the charge is instant.
