### ISSUE TITLE
Issue with save file

### ISSUE THREAD

**Issue by Drapsheik** [daleao/modular-overhaul#52]
I am not sure what went wrong. At first I thought it might have been an error in compatibility with Shared Professions.
I unlocked the sewers after raising Marlons friendship (SVE). I met Krobus. Went to sleep, game saved, woke up and then quit the game.
Now my save won't load at all. It gets stuck on "Loading..."
I have another save and it loads properly with the mods I have.
I would appreciate any help I can get.

My SMAPI Log: https://smapi.io/log/c149119f50b44cccbe49f6383d0c4c0d

**Comment by daleao** [comment]
I don't see anything wrong in your SMAPI log, nor is there anything in this mod tied to Krobus that could cause this issue. Instead of going to pure vanilla for comparison, which doesn't give you much information, I suggest that you disable mods individually until the game works again, which will give you your culprit.

Start by removing this mod, and if that alone solves your issue, then treat each module as a mod and try disabling each one of those one at a time. Report back your findings.

**Comment by Drapsheik** [comment]
I disabled ModularOverhaul and it keeps getting stuck.

I tried using an earlier save from 7 days before with all mods included and it worked. This makes me assume I did something within those 7 days.
- Friend built a tractor garage
- I installed Artisan Valley and all required files. Built a couple sheds and put some of the new machines inside of them.
- I unlocked sewers, talked to Krobus and talked to the statue (did not use it)

I read Tractor Mod is supposed to be built by the main player. My friend built in instead (the day of the crash is the day the tractor's garage was finalized) -  I tried editing the map to remove the tractor garage and delete the tractor before disabling the mod.
Game still crashed.

Regarding Artisan Valley and related mods, I removed all machines with save editor. Disabled the mods but save file would still not load. I attempted to use the earlier save to build a lot of machines related to the mods and use them. slept to save, exit and save loaded properly.

Earlier I mentioned Shared Professions with Prestige. When I clicked the statue to make an offering, it told me I had already prestiged on my combat profession once before. I believe this is because My friend had Amazon and I had Bushwacker. (But same professions in everything else)

CBJCheats also showed a couple checkmarks (skills tab) on Brute(Brute/Amazon) and Defender(Bushwhacker).

I disabled shared professions. Using the 7 day earlier save (before I unlocked sewers), I made sure to have only one lvl 5 and one lvl 10 profession for each skill. Then re-unlocked the sewers, talked to Krobus and the statue (without using it). Slept to save, exit and game loaded save properly.

I attempted to disable all mods as well but my save file was still failing to load.

I thought it might be a memory problem but I can load all mods without issue on other saves.
![image](https://github.com/daleao/modular-overhaul/assets/67082212/eb1ef7fe-771e-43e2-94b8-44d2c030a508)


**[Json Assets] Building map to resolve normal objects.** is the only line that reads on SMAPI right before the game stops responding.

![image](https://github.com/daleao/modular-overhaul/assets/67082212/08d6dc9e-91da-4f31-b64b-7e32620f5e4d)

is my save file corrupted?

Do I just not have enough ram(16gb) for these mods?

**Comment by daleao** [comment]
Thanks for confirming the issue is not with this mod.
But you were not supposed to stop at this mod.
As I said, keep removing mods one-by-one until the save works again.

It's obviously not a RAM issue, although 10 GB is a pretty insane before even finishing the load stage.
You might have a memory leak.How does that compare with your RAM consumption when you first begin loading? For how long was your game loading before you captured that screenshot?
Before you start removing mods, do another test while monitoring closely your Task Manager as the game starts up, click load and wait for ~5 mins.
