### ISSUE TITLE
Unable to generate config file with newest version.

### ISSUE THREAD

**Issue by Rais-Codex** [daleao/modular-overhaul#6]
After installing the mod and (with space core and mod config menu), after version 3.1.1, it does not show up the confirmation menu on first boot up, and it doesn't create a config in either the config menu or the mod folder after closing the game.

**Comment by Rais-Codex** [comment]
I did as the installation guide said to do, but it still did not create a Config file.

**Comment by daleao** [comment]
The only way a mod could _not_ generate a config is if the mod wasn't loaded at all, which could happen due to incorrect installation or missing requirements.
Config generation is handled entirely by SMAPI, which the mod has no control over.

Please share your full log as described in the readme if you require support.

**Comment by Milkyvish** [comment]
> The only way a mod could _not_ generate a config is if the mod wasn't loaded at all, which could happen due to incorrect installation or missing requirements. Config generation is handled entirely by SMAPI, which the mod has no control over.
> 
> Please share your full log as described in the readme if you require further support.

hey i have been trying to launch this for like 2 hours now and everytime i launch smapi i get this message.

Modular Gameplay Overhaul 3.1.2-Debug because its DLL 'DaLion.Overhaul.dll' doesn't exist.

and i dont know what i am supposed to do to solve this issue i would love some help i have been dying to play this and finally got a good enough computer
