### ISSUE TITLE
can't join multiplayer game & game breaks when using galaxy sword/blade of ruins

### ISSUE THREAD

**Issue by salamilover2000** [daleao/modular-overhaul#81]
I am not sure what the problem is but I can't join multiplayer game at all (it either freezes at loading in or says "no available cabin" or that I'm already connected). SMAPI log says that there is an error in the XML document that doesn't recognize Mods_DaLion_DaggerEnchantment
This is my log (https://smapi.io/log/a26d6cce6d364f6481da7cd57b4a487b)

On top of that, the game host seems to be having problems every time they use Galaxy Sword and Blade of Ruins (presumably any MARGO-related weapons), their character would freeze entirely while everything else continues to work.
This is their log (https://smapi.io/log/54246442a3f042fc809f3db32ae46d2a)

We assume that it has something to do with save file, but still have no idea what's going on.

**Comment by daleao** [comment]
Please make sure that all players have the same gameplay config settings.
The same modules should be active on all players.

Key gameplay settings like `EnableWeaponOverhaul` should also be the same, and they should only be changed while all players are online, in order to allow the mod to undo changes and apply fixes.

Based on the logs it looks like some modules may be different between you and the host. I can't confirm it but it also seems like the Combat module is not active on the host, and that has corrupted some of your items.

To resolve this, start by having the host enable the Combat module.
Next, have them supply you with a copy of their config.json to ensure you both have the same settings.
Then, you should be able to join the game. And if the host still wishes to disable the combat module, then you both should do it while online together (them first, then you).

**Comment by salamilover2000** [comment]
We were able to fix this, so just wanted to give you an update:

We had the host completely remove existing MARGO folder, and redownloaded the mod, then they went in solo with Combat module and `EnableWeaponOverhaul` on, then revalidate each of the weapon. However, the `mrg revalidate` command didn't work, and we used `cmbt revalidate` instead on each of the weapon. They sent me their config.json and I also did the same revalidating process. Then we saved.

So far everything is working again (no freezing on entering game, no hanging when sleeping, no freezing when using weapons, damage is consistent with weapon).

Thank you for the help!
