### ISSUE TITLE
Frame Drops When Activating Quest-related Scenes

### ISSUE THREAD

**Issue by PurpleManiac** [daleao/modular-overhaul#9]
Firstly, I would like to thank you for the mod and for being diligently committed to constantly improving it.

I come here to report something that I have suffered every time I reach a certain level of friendship that is related to the sword of darkness quest.

For example, I reached a friendship level with Alex where I can receive quest merit. Even though it is still "NOT" started, my game is experiencing frame drops every 5, 10 seconds of MARGO trying to somehow access my response to Alex's scene.

The game stutters until I watch the scene and compute my answer. Not just Alex, but all the scenes when I reach friendship happen the same way.

I don't understand programming and I'm a game lover and I would like to know if there is any way to minimize the problem I'm having. I remain at your disposal for more information.

**Comment by daleao** [comment]
I think the translation may have created some confusion so let me begin  by clarify something:
Friendship has no impact on the "sword of darkness" (Blade of Ruin) quest.
The quest cares only about your responses during a few key heart events, which it only checks on the moment when you click the response.
This mod does **not** make any time-based checks, and does not make checks repeatedly for that questline.

That said, I did not understand from your description whether the issue occurs all the time after you have reached X hearts with Alex, or if it happens only during event scenes. I'm also curious what would make you suspect that the issue is related to the Blade of Ruin.

If you would like me to look into this you need you to share both your Save and Mods folders.
Also, please attach your complete uploaded SMAPI log as described in the [starting page](https://github.com/daleao/modular-overhaul#reporting-bugs-or-issues).

**Comment by PurpleManiac** [comment]
Hello! Thank you for the response and clarifications.

Yes, I am not an English speaker and I use a translator to try to communicate. I apologize for any confusion.

I currently use 240 mods, but the only ones (I think) that update in ticks are automate and MARGO and that's why I'm suspicious, if MARGO doesn't keep checking the scenes related to the mission "Blade of Ruin" all the time, I'll be calmer, but I really have problems of the nature I mentioned. I'm going to play a game exclusively using MARGO to see how well written it really is and how it brings a profound and incredible improvement to Stardew Valley.

My log:

https://smapi.io/log/34f844e0375c467c94556e94d4852421

I would like, if possible, to ask questions:

Why was MARGO removed from Nexus mod?

About using magnet baits on crabpots. I am receiving iridium quality ores, artifacts and treasure chests when I use my Luremaster profession, is this correct?

The trapper profession says that I can improve the quality of the fish over time. But when I reach level 10 I already receive 100% irido quality, which makes it irrelevant to use, for example, magic baits because of the quality, although the benefit of catching fish from other seasons is really very advantageous.

**Comment by daleao** [comment]
Looking at your log, iyou have a whole bunch of mods that are likely to run events and checks repeatedly in the background.

"I don't know if it's MARGO's fault, but if my collection chest is full, he keeps trying to force it and keeps blocking my FPS. My temporary solution was to add more trunks..."
It sounds like you are making guesses, but do you have any evidence that your FPS issue is related to the full chest?
Like I said, I need you to test with a **minimal** list of mods, such as **only** MARGO, SpaceCore, Automate, CJB Cheats and Item Spawner (spawn a Crab Pot, a Chest and some Magnet Bait, and set Crab Pot processing time to instant in CJB).
I just ran this test locally, and even when the Chest is full, there is no FPS loss or any issue.
I cannot help you unless you can demonstrate that the issue is caused by MARGO and can provide me step by step how to replicate it.

"About using magnet baits on crabpots. I am receiving iridium quality ores, artifacts and treasure chests when I use my Luremaster profession, is this correct?"
No, that does not sound correct.
In my test, I am received only normal quality items. Again: _test with only MARGO and the required mods_.

"The trapper profession says that I can improve the quality of the fish over time. But when I reach level 10 I already receive 100% irido quality, which makes it irrelevant to use, for example, magic baits because of the quality, although the benefit of catching fish from other seasons is really very advantageous."
The Trapper profession does **not** work like Ecologist and Gemologist. Trapper simply unlocks higher qualities. There is no guaranteed quality, nor "over time" progression. Regular Trapper (level 5) also only allows quality up to Gold; you need the prestige version (level 15) to get Iridium.

In total you have described 3 different issues. None of these I was able to reproduce myself. I am inclined to believe it's some sort of mod conflict on your end.
